AssociationsExample/config/routes.rb
AssociationsExample::Application.routes.draw do
  get "items/index"

  get "items/show"

  get "items/new"

  get "items/edit"

  resources :orders do	
    resources :items
  end

end

AssociationsExample/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :order
  attr_accessible :item_name
end

AssociationsExample/app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :order_name

  has_many :items
end

AssociationsExample/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /orders/1/items
  def index
    # For URL like /orders/1/items
    # Get the order with id=1
    @order = Order.find(params[:order_id])
    # Access all items for that order
    @items = @order.items
  end

  # GET /orders/1/items/2
  def show
    @order = Order.find(params[:order_id])
    # For URL like /orders/1/items/2
    # Find an item in orders 1 that has id=2
    @item = @order.items.find(params[:id])
  end

  # GET /orders/1/items/new
  def new
    @order = Order.find(params[:order_id])
    # Associate an item object with order 1
    @item = @order.items.build
  end

  # POST /orders/1/items
  def create
    @order = Order.find(params[:order_id])
    # For URL like /orders/1/items
    # Populate an item associate with order 1 with form data
    # Order will be associated with the item
    @item = @order.items.build(params[:item])
    if @item.save
      # Save the item successfully
      redirect_to order_item_url(@order, @item)
    else
      render :action => "new"
    end
  end

  # GET /orders/1/items/2/edit
  def edit
    @order = Order.find(params[:order_id])
    # For URL like /orders/1/items/2/edit
    # Get item id=2 for order 1
    @item = @order.items.find(params[:id])
  end

  # PUT /orders/1/items/2
  def update
    @order = Order.find(params[:order_id])
    @item = Item.find(params[:id])
    if @item.update_attributes(params[:item])
      # Save the item successfully
      redirect_to order_item_url(@order, @item)
    else
      render :action => "edit"
    end
  end

  # DELETE /orders/1/items/2
  def destroy
    @order = Order.find(params[:order_id])
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_path(@order) }
      format.xml { head :ok }
    end
  end

end

AssociationsExample/app/views/items/_form.html.erb
<%= form_for([@order, @item]) do |f| %>
<% if @item.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@item.errors.count, "error") %> prohibited this order from being saved:</h2>
	<ul>
		<% @item.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="field">
	<p>
		<%= f.label :item_name %>
		<br />
		<%= f.text_field :item_name %>
	</p>
</div>
<div class="actions">
	<%= f.submit %>
</div>
<% end %>

AssociationsExample/app/views/items/edit.html.erb
<h1>Editing item</h1>
<%= render 'form' %>
<%= link_to 'Show', order_item_path(@order, @item) %> |
<%= link_to 'Back', order_items_path(@order) %>

AssociationsExample/app/views/items/index.html.erb
<h1>Items in <%= @order.order_name %></h1>
<table>
	<tr>
		<th>Item name</th>
	</tr>
	<% for item in @items %>
	<tr>
		<td><%= item.item_name %></td>
		<td><%= link_to 'Show', order_item_path(@order, item) %></td>
		<td><%= link_to 'Edit', edit_order_item_path(@order, item) %></td>
		<td><%= link_to 'Destroy', order_item_path(@order, item), :confirm =>
		'Are you sure?', :method => :delete %></td>
	</tr>
	<% end %>
</table>
<br />
<%= link_to 'New item', new_order_item_path(@order) %>
<%= link_to 'Back to Order', @order %>

AssociationsExample/app/views/items/new.html.erb
<h1>New item</h1>
<%= render 'form' %>
<%= link_to 'Back', order_items_path(@order) %>

AssociationsExample/app/views/items/show.html.erb
<h1>Item in <%= @order.order_name %></h1>
<p>
	<b>Item name:</b>
	<%= @item.item_name %>
</p>
<%= link_to 'Edit', edit_order_item_path(@order, @item) %> |
<%= link_to 'Back', order_items_path(@order) %>

AssociationsExample/app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_name %><br />
    <%= f.text_field :order_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AssociationsExample/app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Order name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.order_name %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

AssociationsExample/app/views/orders/show.html.erb
<p>
	<b>Order name:</b>
	<%= @order.order_name %>
</p>
<!-- Display items of an order -->
<h2>Items</h2>
<% @order.items.each do |item| %>
<p>
	<b>Item name:</b>
	<%= item.item_name %>
</p>
<% end %>
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %> |
<%= link_to 'Show Items', order_items_path(@order) %>